#pragma once

#define MASTER_LEFT

#ifdef RGBLIGHT_ENABLE
    #define RGBLIGHT_EFFECT_BREATHING
    #define RGBLIGHT_EFFECT_RAINBOW_MOOD
    #define RGBLIGHT_EFFECT_RAINBOW_SWIRL
    #define RGBLIGHT_EFFECT_SNAKE
    #define RGBLIGHT_EFFECT_KNIGHT
    #define RGBLIGHT_EFFECT_CHRISTMAS
    #define RGBLIGHT_EFFECT_STATIC_GRADIENT
    // #define RGBLIGHT_EFFECT_RGB_TEST
    // #define RGBLIGHT_EFFECT_ALTERNATING
    // #define RGBLIGHT_EFFECT_TWINKLE
    #define RGBLIGHT_LIMIT_VAL 120
    #define RGBLIGHT_HUE_STEP 10
    #define RGBLIGHT_SAT_STEP 17
    #define RGBLIGHT_VAL_STEP 17
    // #define RGBLIGHT_HUE_STEP 8
    // #define RGBLIGHT_SAT_STEP 8
    // #define RGBLIGHT_VAL_STEP 8
#endif

// VIA
#define DYNAMIC_KEYMAP_LAYER_COUNT 5

// Tri Layers
// #define TRI_LAYER_LOWER_LAYER 1
// #define TRI_LAYER_UPPER_LAYER 2
// #define TRI_LAYER_ADJUST_LAYER 3
